### ISSUE TITLE
Bac's Pack Bugs

### ISSUE THREAD

**Issue by o2dganon** [Slate5521/RTB-Reloaded#1]
Deep Seas map is broke
ER2701 command on The Isles causes a crash

**Comment by Slate5521** [comment]
I did some experimenting, and the deep seas crash has to do with particles.

**Comment by Slate5521** [comment]
I have fixed the Deep Seas crash. 

Just as a note to myself... It was occurring because the sea bubble emitter had dependencies on SmokeParticleEmitterNode, which is executed after the map. Knowing this, I should probably make SmokeParticleEmitterNode among the first datablocks to be executed upon server creation, which will theoretically fix the ER2701 crash.

**Comment by Slate5521** [comment]
Okay, I'm leaving this as a note to myself--I fixed the Deep Seas crash while retaining its particles because I have defined the particle/particleemitter datablocks in question (within particles.cs) before the mission is loaded (onServerCreated call). The crash is occurring because the datablocks themselves were attached to the mission file, which is in its entirety being loaded when the game attempts to call buildLoadInfo via loadMission. 

Now, hopefully this shouldn't be an issue for people (haha like we're ever gonna get any people playing RTB) wanting to create custom particles for use in their own map. All they have to do is toss the definitions inside literally any of the server files that are executed upon server creation.

**Comment by Slate5521** [comment]
I did the same thing to The Isles, which makes it work. I'd like to point out that, in doing this, I've effectively just chewed up 12 whole datablocks. If we ever need to clear some datablocks up because we hit the limit, we should remove the island's volcano stuff if we cannot find anything else.

**Comment by Slate5521** [comment]
...for some reason, trying to execute & use these particle datablocks after Brickprints.cs is executed causes a crash.

**Comment by Slate5521** [comment]
This has been fixed at the cost of another bug springing up, but that's just because RTB. If you try switching to maps like Deep Seas or The Islands after you are already in the map, the game won't crash, but the particles won't load.
